[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pyairports"
version = "0.0.0"
description = "Minimal stub for pyairports"
authors = [{ name = "stub" }]
requires-python = ">=3.8"
